SheffieldWebApp/Models/Student.cs
namespace SheffieldWebApp.Models

{
    public class Student
    {
        public int Id { get; set; }
        public string RegistrationId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime DateOfBirth { get; set; }
        public int Phone { get; set; }
        public string Address { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int GradeId { get; set; }
    }
}

SheffieldWebApp/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SheffieldWebApp.Data;
using SheffieldWebApp.Models;
using static Azure.Core.HttpHeader;

namespace SheffieldWebApp.Controllers
{
    public class StudentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Students

        public async Task<IActionResult> Index()
        {
            return View(await _context.Student.ToListAsync());
        }

        // GET: Students/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            List<Mark> studentMarks = await _context.Mark.Where(m => m.StudentId == student.Id.ToString()).ToListAsync();
            List<AssignedStudent> studentAssignedSubjects = await _context.AssignedStudents.Where(a => a.StudentId == student.RegistrationId).ToListAsync();
            List<Subject> allSubjects = await _context.Subject.ToListAsync();
            List<Subject> studentSubjects = [];  

            foreach (var item in allSubjects)
            {
                foreach(var subject in studentAssignedSubjects)
                {
                    if(item.Id == subject.SubjectId)
                    {
                        studentSubjects.Add(item);
                    }
                }
            }
            ViewData["marks"] = studentMarks;
            ViewData["studentSubject"] = studentSubjects;

            return View(student);
        }

        // GET: Students/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,RegistrationId,Name,Email,DateOfBirth,GradeId")] Student student)
        {
            if (ModelState.IsValid)
            {
                _context.Add(student);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student.FindAsync(id);
            if (student == null)
            {
                return NotFound();
            }
            return View(student);
        }

        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,RegistrationId,Name,Email,DateOfBirth,GradeId")] Student student)
        {
            if (id != student.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(student);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StudentExists(student.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }

        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var student = await _context.Student
                .FirstOrDefaultAsync(m => m.Id == id);
            if (student == null)
            {
                return NotFound();
            }

            return View(student);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var student = await _context.Student.FindAsync(id);
            if (student != null)
            {
                _context.Student.Remove(student);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StudentExists(int id)
        {
            return _context.Student.Any(e => e.Id == id);
        }
    }
}

SheffieldWebApp/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SheffieldWebApp.Data;
using SheffieldWebApp.Models;

namespace SheffieldWebApp.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SubjectsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
            return View(await _context.Subject.ToListAsync());
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id, int? userId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject
                .FirstOrDefaultAsync(m => m.Id == id);

            if (subject == null)
            {
                return NotFound();
            }

            var grades = await _context.Grade
                .Where(g => g.SubjectName == subject.Title)
                .ToListAsync();

            var viewModel = new SubjectDetailsViewModel
            {
                Subject = subject,
                Grades = grades
            };
            ViewBag.UserId = userId;
            return View(viewModel);
        }


        // GET: Subjects/Create
        public IActionResult Create()
        {
            return View();
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Admin");
            }
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                if (User.IsInRole("Admin"))
                {
                    return RedirectToAction("Index", "Admin");

                }
                return RedirectToAction("Index", "TeachersDashboard");

            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var subject = await _context.Subject
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var subject = await _context.Subject.FindAsync(id);
            if (subject != null)
            {
                _context.Subject.Remove(subject);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction("Index", "Admin");
        }

        private bool SubjectExists(int id)
        {
            return _context.Subject.Any(e => e.Id == id);
        }
    }
}

SheffieldWebApp/Views/Students/Create.cshtml
@model SheffieldWebApp.Models.Student

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Student</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="RegistrationId" class="control-label"></label>
                <input asp-for="RegistrationId" class="form-control" />
                <span asp-validation-for="RegistrationId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateOfBirth" class="control-label"></label>
                <input asp-for="DateOfBirth" class="form-control" />
                <span asp-validation-for="DateOfBirth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GradeId" class="control-label"></label>
                <input asp-for="GradeId" class="form-control" />
                <span asp-validation-for="GradeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SheffieldWebApp/Views/Students/Delete.cshtml
@model SheffieldWebApp.Models.Student

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Student</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegistrationId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegistrationId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GradeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GradeId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SheffieldWebApp/Views/Students/Details.cshtml
@model SheffieldWebApp.Models.Student

@{
    ViewData["Title"] = "Details";
    List<Subject> subjects = ViewData["studentSubject"] as List<Subject> ?? [];
    List<Mark> marks = ViewData["marks"] as List<Mark> ?? [];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if(User.IsInRole("Student")){
    <h1>Hello @Model.Name</h1>
}

<div class="card mt-4 shadow">
    <div class="card-header"><h5>Profile Details</h5></div>
    <div class="card-body">
        <div>
            <h4>Student</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">
                    Student Id
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Id)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.Email)
                </dd>
                <dt class="col-sm-3">
                    @Html.DisplayNameFor(model => model.DateOfBirth)
                </dt>
                <dd class="col-sm-9">
                    @Html.DisplayFor(model => model.DateOfBirth)
                </dd>
            </dl>
        </div>
        <div>
            <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model?.Id">Edit</a>
            
        </div>
    </div>
</div>

<div class="card shadow mt-4">
    <div class="card-header"><h5>Assigned Subjects</h5></div>
    <div class="card-body">
        <table class="table table-hover">
            @foreach (var subject in subjects){
                <tr>
                    <td class="col-10">@subject.Title</td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Subjects" asp-action="Details" asp-route-userId="@Model!.Id" asp-route-id="@subject.Id">Details</a>
                    </td>
                </tr>
            }
        </table>
           
    </div>
</div>


<div class="card shadow mt-4">
    <div class="card-header"><h5>Subject Marks</h5></div>
    <div class="card-body">

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">Subject</th>
                    <th scope="col">Marks</th>
                    <th scope="col">Grade</th>
                </tr>
            </thead>
            
            @foreach (var mark in marks)
            {
                Subject subjectName = subjects.FirstOrDefault(s => s.Id == mark.SubjectId)!;
                <tr>
                    <td>@subjectName.Title</td>
                    <td>@mark.MarksObtained</td>
                    <td>@mark.GradeName</td>
                </tr>
            }
            
        </table>
        
    </div>
</div>

SheffieldWebApp/Views/Students/Edit.cshtml
@model SheffieldWebApp.Models.Student

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex justify-content-center">
    <div class="card mt-4 shadow" style="width: 50%;">
        <div class="card-header text-center">
            <h4 class="mt-3">Edit Student Profile</h4>
        </div>
        <div class="card-body">
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <input asp-for="RegistrationId" class="form-control" value="@Model.RegistrationId" type="hidden" />
                    <span asp-validation-for="RegistrationId" class="text-danger"></span>
                </div>

                <div class="form-group mt-3">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>

                <div class="form-group mt-3">
                    <label asp-for="Email" class="control-label"></label>
                    <input asp-for="Email" class="form-control" readonly value="@Model.Email" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>

                <div class="form-group mt-3">
                    <label asp-for="DateOfBirth" class="control-label"></label>
                    <input asp-for="DateOfBirth" type="date" class="form-control" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>

                <div class="form-group mt-3">
                    <input asp-for="GradeId" class="form-control" type="hidden" value="0" />
                    <span asp-validation-for="GradeId" class="text-danger"></span>
                </div>

                <div class="form-group text-center mt-4">
                    <input type="submit" value="Save" class="btn btn-primary col-8" />
                </div>
            </form>
        </div>
    </div>
</div>

<div class="text-center mt-3">
    @if(User.IsInRole("Admin")){
        <a asp-action="Index" asp-controller="Admin" class="btn btn-secondary">Back to List</a>
    }else{
        <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary">Back to List</a>
    }
</div>

SheffieldWebApp/Views/Students/Index.cshtml
@model IEnumerable<SheffieldWebApp.Models.Student>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.RegistrationId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateOfBirth)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GradeId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegistrationId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateOfBirth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GradeId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>